apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgDIdoeDu6+AVafaPLL8dcHRiyBGfEFA2TbxOJ9synrTBcazkJzseYuNvN5FX7LknGFVo+M3XZuRgIVdUoDMW2I+KcyXRD6/NLPCbI0kdoNtQsOq5eJZ7/TAV74E7rPwfJscCmjW6OoE/aD6HD/4xOLe4pREfhGk1KQ9ZIqFyG6k/vNRNX9l7re4chWnkPF/QVKeFPPmkyYanyWwSnPXyE7BM8lplF54uF1qG6zZDxeYlLx7eZD0MsAhGHFlCLMiMpOXtIP7FroPRih87hC0wcaSuirDc0dVoHwAKGeM9xz00of70odzISkErVgji6TkYRNsiy5JgdbuyCTs1W9Z+GYNN78btHVwe85UmDR5eEXbsezyPVKru8cbP/I0Ixjfi/G/+P0BviDTejHlPrTBLUuYmquzwyI2D3/tbZiR4b71oYS+b51UJ5KBjwFjSb4jUDlMgKiADHLyCRqJlta11PfivIhBQ7/3Fyapkr4KNxpbP/vqn9jUtgCdv0xk+N3NQ3Rmb1IKt364aX94/RNfzFbl98w8WynAqs/6PCYVElTReq6tfUpoLdffDoJYZg28vTHwbxrQmVLFyeF43+F6uTYzGr937FMYcNpzcD0BNl3ikAR3dTPIMBUZ+QJsTMxlKRip4l+WBSaeh6S6pUjBjAsnn8sltXo0qj92mLo37X1svGztAeArFhUebY5NhUqkwyjbHHULLxob
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app

