---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: .
    repoURL: https://github.com/atoy3731/hello-world-manifests.git
    targetRevision: master
    helm:
      values: |
        replicaCount: 5

        ingress:
          annotations:
            kubernetes.io/ingress.allow-http: "false"
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - host: demo-app.k8s.intra
          tls:
            - secretName: demo-app-tls
              hosts:
                - demo-app.k8s.intra
